//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLisa.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        MVCLisa.ServiceReference1.HelloWorldResponse HelloWorld(MVCLisa.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCLisa.ServiceReference1.HelloWorldResponse> HelloWorldAsync(MVCLisa.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 id 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAge", ReplyAction="*")]
        MVCLisa.ServiceReference1.GetAgeResponse GetAge(MVCLisa.ServiceReference1.GetAgeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAge", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCLisa.ServiceReference1.GetAgeResponse> GetAgeAsync(MVCLisa.ServiceReference1.GetAgeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public MVCLisa.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(MVCLisa.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVCLisa.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(MVCLisa.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAgeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAge", Namespace="http://tempuri.org/", Order=0)]
        public MVCLisa.ServiceReference1.GetAgeRequestBody Body;
        
        public GetAgeRequest() {
        }
        
        public GetAgeRequest(MVCLisa.ServiceReference1.GetAgeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAgeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public GetAgeRequestBody() {
        }
        
        public GetAgeRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAgeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAgeResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVCLisa.ServiceReference1.GetAgeResponseBody Body;
        
        public GetAgeResponse() {
        }
        
        public GetAgeResponse(MVCLisa.ServiceReference1.GetAgeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAgeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAgeResult;
        
        public GetAgeResponseBody() {
        }
        
        public GetAgeResponseBody(string GetAgeResult) {
            this.GetAgeResult = GetAgeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : MVCLisa.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<MVCLisa.ServiceReference1.WebService1Soap>, MVCLisa.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCLisa.ServiceReference1.HelloWorldResponse MVCLisa.ServiceReference1.WebService1Soap.HelloWorld(MVCLisa.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            MVCLisa.ServiceReference1.HelloWorldRequest inValue = new MVCLisa.ServiceReference1.HelloWorldRequest();
            inValue.Body = new MVCLisa.ServiceReference1.HelloWorldRequestBody();
            MVCLisa.ServiceReference1.HelloWorldResponse retVal = ((MVCLisa.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCLisa.ServiceReference1.HelloWorldResponse> MVCLisa.ServiceReference1.WebService1Soap.HelloWorldAsync(MVCLisa.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCLisa.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            MVCLisa.ServiceReference1.HelloWorldRequest inValue = new MVCLisa.ServiceReference1.HelloWorldRequest();
            inValue.Body = new MVCLisa.ServiceReference1.HelloWorldRequestBody();
            return ((MVCLisa.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCLisa.ServiceReference1.GetAgeResponse MVCLisa.ServiceReference1.WebService1Soap.GetAge(MVCLisa.ServiceReference1.GetAgeRequest request) {
            return base.Channel.GetAge(request);
        }
        
        public string GetAge(string id) {
            MVCLisa.ServiceReference1.GetAgeRequest inValue = new MVCLisa.ServiceReference1.GetAgeRequest();
            inValue.Body = new MVCLisa.ServiceReference1.GetAgeRequestBody();
            inValue.Body.id = id;
            MVCLisa.ServiceReference1.GetAgeResponse retVal = ((MVCLisa.ServiceReference1.WebService1Soap)(this)).GetAge(inValue);
            return retVal.Body.GetAgeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCLisa.ServiceReference1.GetAgeResponse> MVCLisa.ServiceReference1.WebService1Soap.GetAgeAsync(MVCLisa.ServiceReference1.GetAgeRequest request) {
            return base.Channel.GetAgeAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCLisa.ServiceReference1.GetAgeResponse> GetAgeAsync(string id) {
            MVCLisa.ServiceReference1.GetAgeRequest inValue = new MVCLisa.ServiceReference1.GetAgeRequest();
            inValue.Body = new MVCLisa.ServiceReference1.GetAgeRequestBody();
            inValue.Body.id = id;
            return ((MVCLisa.ServiceReference1.WebService1Soap)(this)).GetAgeAsync(inValue);
        }
    }
}
